services:
  postgres:
    container_name: postgres
    image: postgres:latest
    environment:
      POSTGRES_DB: products
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: mbCjj9Ext
    ports:
      - '5432:5432'
    restart: unless-stopped
